version: 2

models:
  - name: stg_transactions
    description: "Cleaned and standardized core banking transactions."
    columns:
      - name: transaction_id
        description: "The primary key for this table."
        tests:
          - unique
          - not_null
      
      - name: transaction_type
        description: "The type of transaction."
        tests:
          - not_null
          - accepted_values:
              arguments:
                values: ['CREDIT', 'DEBIT']
              
      - name: transaction_amount
        description: "The financial value of the transaction."
        tests:
          - not_null